export const GET_PASSENGERS = "GET_PASSENGERS";
export const API_PASSENGERS_RESPONSE_SUCCESS = "API_PASSENGERS_RESPONSE_SUCCESS";
export const API_PASSENGERS_RESPONSE_ERROR = "API_PASSENGERS_RESPONSE_ERROR" ;
export const ADD_PASSENGER = "ADD_PASSENGER";