export const GET_PROFILS = "GET_PROFILS";
export const API_PROFILS_RESPONSE_SUCCESS = "API_PROFILS_RESPONSE_SUCCESS";
export const API_PROFILS_RESPONSE_ERROR = "API_PROFILS_RESPONSE_ERROR" ;
export const ADD_PROFIL = "ADD_PROFIL";
export const UPDATE_PROFIL = "UPDATE_PROFIL" ;
export const DELETE_PROFIL = "DELETE_PROFIL" ;